### ISSUE TITLE
大佬，有点没看懂，如果能解释一下原理就好了。

### ISSUE THREAD

**Issue by supperlitt** [WangYinuo/MemDump#1]
如果能解释一下原理就好了。

**Comment by WangYinuo** [comment]
可以了解一下 linux 的 ptrace函数


发自我的 iPhone

在 2018年7月5日，11:49，超级_小小 <notifications@github.com<mailto:notifications@github.com>> 写道：


如果能解释一下原理就好了。

**Comment by WangYinuo** [comment]
核心就是ptrace的原理 附加到目标进程

**Comment by WangYinuo** [comment]
done
